AlumniSite/Controllers/AlumniUsersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlumniSite.Contexts;
using AlumniSite.Models;
using static AlumniSite.Data.Security;

namespace AlumniSite.Controllers
{
    public class AlumniUsersController : Controller
    {
        private readonly TrackerContext _context;

        public AlumniUsersController(TrackerContext context)
        {
            _context = context;
        }

        // GET: AlumniUsers
        public async Task<IActionResult> Index() //replace this to be search, and then use general input?
        {
            var trackerContext = _context.AlumniUsers.Include(a => a.Address).Include(a => a.Employer);
            return View(await trackerContext.ToListAsync());
        }

        // GET: AlumniUsers/Details/5
        public async Task<IActionResult> Details(int? id) // be able to map random numbers to an id per session
        {
            if (id == null) 
            {
                return NotFound();
            }
            var alumniUser = await _context.AlumniUsers
                .Include(a => a.Address)
                .Include(a => a.Employer)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (alumniUser == null)
            {
                return NotFound();
            }

            return View(alumniUser);
        }

        // GET: AlumniUsers/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressId");
            ViewData["EmployerId"] = new SelectList(_context.Employers, "EmployerId", "EmployerId");
            return View();
        }

        // POST: AlumniUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,UserPw,IsAdmin,AddressId,EmployerId,EmployerName,YearGraduated,Degree,Notes,AdminType,DateModified")] AlumniUser alumniUser)
        {
            if(CheckInputs(alumniUser))
            {
                return View();
            }
            if (ModelState.IsValid)
            {
                _context.Add(alumniUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressId", alumniUser.AddressId);
            ViewData["EmployerId"] = new SelectList(_context.Employers, "EmployerId", "EmployerId", alumniUser.EmployerId);
            return View(alumniUser);
        }
        public static bool CheckInputs(AlumniUser alumniUser)
        {
            bool[] goodInput = new bool[18];
            goodInput[0] = GeneralInput(alumniUser.Username);
            goodInput[1] = GeneralInput(alumniUser.UserPw);
            // User Address Block
            goodInput[2] = GeneralInput(alumniUser.Address.Address1);
            goodInput[3] = GeneralInput(alumniUser.Address.City);
            goodInput[4] = GeneralInput(alumniUser.Address.State);
            goodInput[5] = GeneralInput(alumniUser.Address.Zip);
            goodInput[6] = PhoneInput(alumniUser.Address.Phone); //Our Phone Number
            //Employer Block
            goodInput[7] = GeneralInput(alumniUser.Employer.EmployerName);
            goodInput[8] = GeneralInput(alumniUser.Employer.Address.Address1);
            goodInput[9] = GeneralInput(alumniUser.Employer.Address.City);
            goodInput[10] = GeneralInput(alumniUser.Employer.Address.State);
            goodInput[11] = GeneralInput(alumniUser.Employer.Address.Zip);
            goodInput[12] = GeneralInput(alumniUser.Employer.Address.Phone);

            goodInput[13] = GeneralInput(alumniUser.EmployerName);
            goodInput[14] = GeneralInput(alumniUser.YearGraduated);
            goodInput[15] = GeneralInput(alumniUser.Degree);
            goodInput[16] = GeneralInput(alumniUser.Notes);

            //PhoneInput(alumniUser.PhoneNumber); //ASP NET Identity Phone Number

            
            
            
            if(!goodInput.Contains(false))
            {
                return true;
            }
            return false;
        }

        // GET: AlumniUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumniUser = await _context.AlumniUsers.FindAsync(id);
            if (alumniUser == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressId", alumniUser.AddressId);
            ViewData["EmployerId"] = new SelectList(_context.Employers, "EmployerId", "EmployerId", alumniUser.EmployerId);
            return View(alumniUser);
        }

        // POST: AlumniUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,UserPw,IsAdmin,AddressId,EmployerId,EmployerName,YearGraduated,Degree,Notes,AdminType,DateModified")] AlumniUser alumniUser)
        {
            if (id != alumniUser.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alumniUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlumniUserExists(alumniUser.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "AddressId", "AddressId", alumniUser.AddressId);
            ViewData["EmployerId"] = new SelectList(_context.Employers, "EmployerId", "EmployerId", alumniUser.EmployerId);
            return View(alumniUser);
        }

        // GET: AlumniUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumniUser = await _context.AlumniUsers
                .Include(a => a.Address)
                .Include(a => a.Employer)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (alumniUser == null)
            {
                return NotFound();
            }

            return View(alumniUser);
        }

        // POST: AlumniUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alumniUser = await _context.AlumniUsers.FindAsync(id);
            _context.AlumniUsers.Remove(alumniUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlumniUserExists(int id)
        {
            return _context.AlumniUsers.Any(e => e.UserId == id);
        }
    }
}

AlumniSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    
    <title>@ViewData["Title"] - AlumniSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlumniSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm">
        <div class="container"> @*this may be cause for formatting issue*@

            

                <div class="col align-self-start float-left">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/Images/Alumni-Logo-01.png" />
                    </a>
                </div>
                        @*sociallinks*@

                <div class="col-1 col align-self-start float-right">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li>
                            <a class="nav-link" href="https://www.linkedin.com/groups/13706636/">
                                <img src="~/Images/LinkedIn.png" />
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="https://www.instagram.com/centralia_college_foundation/">
                                <img src="~/Images/Instagram.png" />
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="https://www.facebook.com/CentraliaCollegeFoundation/">
                                <img src="~/Images/Facebook.png" />
                            </a>
                        </li>
                    </ul>
                </div>

                    @*navigationlinks*@
                <div class=" col-5 align-self-end float-right">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 justify-content-end">
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle nav-link text-dark navi" @*data-toggle="dropdown" Not sure what this is, but seems to work without*@ 
                                    href="https://www.centraliacollegealumni.org/">
                                    About
                                </a>
                            
                                <ul class="dropdown-menu" 
                                    role="menu">
                                    <li><a class="nav-link dropdown-item " href="https://www.centraliacollegealumni.org/faq">FAQ</a></li>
                                    <li><a class="nav-link dropdown-item " href="https://www.centraliacollegealumni.org/contact">Contact</a></li>
                                    <li><a class="nav-link dropdown-item " href="https://www.centraliacollegealumni.org/donate">Donate</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle navi" 
                                href="https://www.centraliacollegealumni.org/news">
                                News
                            </a>

                            <ul class="dropdown-menu clearfix" 
                                role="menu">
                                <li><a class="nav-link dropdown-item" href="https://www.centraliacollegealumni.org/update">Spotlight Form</a></li>
                            </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle navi" 
                                href="https://www.centraliacollegealumni.org/resources">
                                Resources
                            </a>

                            <ul class="dropdown-menu clearfix" 
                                role="menu">
                                <li><a class="nav-link dropdown-item" href="https://www.centraliacollegealumni.org/zoom-backgrounds">Zoom Backgrounds</a></li>
                                <li><a class="nav-link dropdown-item" href="https://www.centraliacollegealumni.org/mentoring">Mentoring</a></li>
                            </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle navi" 
                                href="https://www.centraliacollegealumni.org/events">
                                Events
                            </a>

                            <ul class="dropdown-menu clearfix" 
                                role="menu">
                                <li><a class="nav-link dropdown-item" href="https://www.centraliacollegealumni.org/service">Community Service</a></li>
                            </ul>
                            </li>
    @*                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AlumniUsers" asp-action="Privacy">Privacy</a>
                            </li>*@
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>

        </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AlumniSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>